services:
  - type: web
    name: ecommerce-backend
    runtime: python
    pythonVersion: "3.9"
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: python -m uvicorn BackendEcommerce:app --host 0.0.0.0 --port 10000
    envVars:
      - key: MONGODB_URL
        value: mongodb+srv://Rohit:Rohit@cluster0.avcsol9.mongodb.net/
      - key: DATABASE_NAME
        value: ecommerce
