services:
  - type: web
    name: ecommerce-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: MONGODB_URL
        value: mongodb+srv://Rohit:Rohit@cluster0.avcsol9.mongodb.net/
      - key: DATABASE_NAME
        value: ecommerce